# my global config
  global:
    scrape_interval: 10s
    evaluation_interval: 10s
 # Alertmanager configuration
 alerting:
   alertmanagers:
     - static_configs:
         - targets:
           # - alertmanager:9093

scrape_configs:
  - job_name: "ultrafeeder"
  static_configs:
    - targets: ["localhost:9273", "localhost:9274"]

  - job_name: "prometheus"
  static_configs: 
    - targets: ["localhost:9090"]

  remote_write:
  - url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
    basic_auth:
      username: 1488847
      password: glc_eyJvIjoiMTA4MjgwNiIsIm4iOiJzdGFjay04ODc4MjAtaG0tcmVhZC1kZWZsaS1kb2NrZXIiLCJrIjoiN2NXNjJpMDkyTmpZUWljSDkwT3NOMDh1IiwibSI6eyJyIjoicHJvZC11cy1lYXN0LTAifX0=
